dist: bionic

language: go

go:
  - 1.13.x
  - 1.10.x

git:
  depth: 1

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go build
  - GOOS=windows GOARCH=amd64 go build

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file:
    - "chronos"
    - "chronos.exe"
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.13
