dist: bionic

language: go

go:
  - 1.13.x
  - 1.10.x

git:
  depth: 1

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go build
  - GOOS=windows GOARCH=amd64 go build

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file:
    - $TRAVIS_BUILD_DIR/chronos
    - $TRAVIS_BUILD_DIR/chronos.exe
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.13

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
